version: '3.9'
services:
  web-server-template:
    container_name: web-server-template
    build:
      context: ../../
      dockerfile: ./Dockerfile/Production/Dockerfile
      target: image
    ports:
      - '8080:8080'