#### Bulding executable
FROM golang:1.18.6 as build-stage
ENV GOENV="development"

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Build Air
RUN go install github.com/cosmtrek/air@5cd62ac

WORKDIR /app
COPY . /app
#COPY go.mod go.sum ./

# Install dependencies
RUN go mod download

ENTRYPOINT ["air", "-c", "./config/air.toml"]