version: '3.9'
services:
  web-server-template:
    container_name: web-server-template-live-reload
    build:
      context: ../../
      dockerfile: ./Dockerfile/Development/Dockerfile.LiveReload
    volumes:
      - ../..:/app
    ports:
      - '8080:8080'
      - '40000:40000'