version: '3.9'
services:
  web-server-template:
    container_name: web-server-template-debug
    build:
      context: ../../
      dockerfile: ./Dockerfile/Development/Dockerfile
    ports:
      - '8080:8080'
      - '40000:40000'
